### ISSUE TITLE
Decoder for LUT

### ISSUE THREAD

**Issue by cmpute** [kevinhartman/morton-nd#8]
Thanks for you excellent work on this! Could we have a decoder for LUT encoder? Target machine for my project probably doesn't support BMI2 or AVX2 so I cannot use the decoder. I really like the templated style in your code but this problem prevents me from using it...

**Comment by kevinhartman** [comment]
Thanks for considering this project! I originally planned to implement a matching constexpr LUT decoder, but didn't get around to it. Optimistically, I may have some time to implement something in the next few weeks.

**Comment by cmpute** [comment]
Thanks for the great work!

**Comment by kevinhartman** [comment]
Thanks for the suggestion! Please feel free to file additional issues if you find something doesn't work well for your use case. There's a [benchmark project](https://github.com/kevinhartman/libmorton#fork-changes) you can use to tune the configuration for your arch/application as well, though keep in mind it may take a while to compile. I'll be updating that repo with the decoder testing added in support of #9 shortly. I'll also be doing an official major version release through Vcpkg in the next few days.
